
export interface LanguageOption {
    code: string;
    name: string;
    localName: string;
    isCommon: boolean;
}

export const LANGUAGES: LanguageOption[] = [
    { code: 'ar', name: 'Arabic', localName: '阿拉伯语', isCommon: true },
    { code: 'as-IN', name: 'Assamese', localName: '阿萨姆语', isCommon: false },
    { code: 'az-AZ', name: 'Azerbaijani', localName: '阿塞拜疆语', isCommon: false },
    { code: 'be-BY', name: 'Belarusian', localName: '白俄罗斯语', isCommon: false },
    { code: 'bg-BG', name: 'Bulgarian', localName: '保加利亚语', isCommon: false },
    { code: 'bn-BD', name: 'Bengali', localName: '孟加拉语', isCommon: false },
    { code: 'bo-CN', name: 'Tibetan', localName: '藏语', isCommon: false },
    { code: 'bs-BA', name: 'Bosnian', localName: '波斯尼亚语', isCommon: false },
    { code: 'ca-ES', name: 'Catalan', localName: '加泰罗尼亚语', isCommon: false },
    { code: 'cs-CZ', name: 'Czech', localName: '捷克语', isCommon: false },
    { code: 'da-DK', name: 'Danish', localName: '丹麦语', isCommon: false },
    { code: 'de-DE', name: 'German', localName: '德语', isCommon: true },
    { code: 'el-GR', name: 'Greek', localName: '希腊语', isCommon: false },
    { code: 'en-US', name: 'English', localName: '英语', isCommon: true },
    { code: 'es-ES', name: 'Spanish', localName: '西班牙语', isCommon: true },
    { code: 'et-EE', name: 'Estonian', localName: '爱沙尼亚语', isCommon: false },
    { code: 'eu-ES', name: 'Basque', localName: '巴斯克语', isCommon: false },
    { code: 'fa-IR', name: 'Persian', localName: '波斯语', isCommon: false },
    { code: 'fi-FI', name: 'Finnish', localName: '芬兰语', isCommon: false },
    { code: 'fr-FR', name: 'French', localName: '法语', isCommon: true },
    { code: 'gl-ES', name: 'Galician', localName: '加利西亚语', isCommon: false },
    { code: 'gu-IN', name: 'Gujarati', localName: '古吉拉特语', isCommon: false },
    { code: 'ha-NG', name: 'Hausa', localName: '豪萨语', isCommon: false },
    { code: 'hi-IN', name: 'Hindi', localName: '印地语', isCommon: true },
    { code: 'hr-HR', name: 'Croatian', localName: '克罗地亚语', isCommon: false },
    { code: 'hu-HU', name: 'Hungarian', localName: '匈牙利语', isCommon: false },
    { code: 'hy-AM', name: 'Armenian', localName: '亚美尼亚语', isCommon: false },
    { code: 'id-ID', name: 'Indonesian', localName: '印尼语', isCommon: true },
    { code: 'it-IT', name: 'Italian', localName: '意大利语', isCommon: true },
    { code: 'he-IL', name: 'Hebrew', localName: '希伯来语', isCommon: false },
    { code: 'ja-JP', name: 'Japanese', localName: '日语', isCommon: true },
    { code: 'ka-GE', name: 'Georgian', localName: '格鲁吉亚语', isCommon: false },
    { code: 'kk-KZ', name: 'Kazakh', localName: '哈萨克语', isCommon: false },
    { code: 'km-KH', name: 'Khmer', localName: '高棉语', isCommon: false },
    { code: 'kn-IN', name: 'Kannada', localName: '卡纳达语', isCommon: false },
    { code: 'ko-KR', name: 'Korean', localName: '韩语', isCommon: true },
    { code: 'lo-LA', name: 'Lao', localName: '老挝语', isCommon: false },
    { code: 'lt-LT', name: 'Lithuanian', localName: '立陶宛语', isCommon: false },
    { code: 'lv-LV', name: 'Latvian', localName: '拉脱维亚语', isCommon: false },
    { code: 'mk-MK', name: 'Macedonian', localName: '马其顿语', isCommon: false },
    { code: 'ml-IN', name: 'Malayalam', localName: '马拉雅拉姆语', isCommon: false },
    { code: 'mn-MN', name: 'Mongolian', localName: '蒙古语', isCommon: false },
    { code: 'mr-IN', name: 'Marathi', localName: '马拉地语', isCommon: false },
    { code: 'ms-MY', name: 'Malay', localName: '马来语', isCommon: true },
    { code: 'mt-MT', name: 'Maltese', localName: '马耳他语', isCommon: false },
    { code: 'my-MM', name: 'Burmese', localName: '缅甸语', isCommon: false },
    { code: 'nb-NO', name: 'Norwegian', localName: '挪威语', isCommon: false },
    { code: 'ne-NP', name: 'Nepali', localName: '尼泊尔语', isCommon: false },
    { code: 'nl-NL', name: 'Dutch', localName: '荷兰语', isCommon: false },
    { code: 'or-IN', name: 'Oriya', localName: '奥里亚语', isCommon: false },
    { code: 'pa-IN', name: 'Punjabi', localName: '旁遮普语', isCommon: false },
    { code: 'pl-PL', name: 'Polish', localName: '波兰语', isCommon: true },
    { code: 'pt-PT', name: 'Portuguese', localName: '葡萄牙语', isCommon: true },
    { code: 'pt-BR', name: 'Portuguese (Brazil)', localName: '葡萄牙语(巴西)', isCommon: true },
    { code: 'ro-RO', name: 'Romanian', localName: '罗马尼亚语', isCommon: false },
    { code: 'ru-RU', name: 'Russian', localName: '俄语', isCommon: true },
    { code: 'si-LK', name: 'Sinhala', localName: '僧伽罗语', isCommon: false },
    { code: 'sk-SK', name: 'Slovak', localName: '斯洛伐克语', isCommon: false },
    { code: 'sl-SI', name: 'Slovenian', localName: '斯洛文尼亚语', isCommon: false },
    { code: 'sq-AL', name: 'Albanian', localName: '阿尔巴尼亚语', isCommon: false },
    { code: 'sr-RS', name: 'Serbian', localName: '塞尔维亚语', isCommon: false },
    { code: 'sv-SE', name: 'Swedish', localName: '瑞典语', isCommon: false },
    { code: 'sw-KE', name: 'Kiswahili', localName: '斯瓦西里语', isCommon: false },
    { code: 'ta-IN', name: 'Tamil', localName: '泰米尔语', isCommon: false },
    { code: 'te-IN', name: 'Telugu', localName: '泰卢固语', isCommon: false },
    { code: 'th-TH', name: 'Thai', localName: '泰语', isCommon: true },
    { code: 'fil-PH', name: 'Filipino', localName: '菲律宾语', isCommon: true },
    { code: 'tr-TR', name: 'Turkish', localName: '土耳其语', isCommon: true },
    { code: 'ug-CN', name: 'Uighur', localName: '维吾尔语', isCommon: false },
    { code: 'uk-UA', name: 'Ukrainian', localName: '乌克兰语', isCommon: true },
    { code: 'ur-PK', name: 'Urdu', localName: '乌尔都语', isCommon: false },
    { code: 'uz-UZ', name: 'Uzbek', localName: '乌兹别克语', isCommon: false },
    { code: 'vi-VN', name: 'Vietnamese', localName: '越南语', isCommon: true },
    { code: 'zh-CN', name: 'Chinese (Simplified)', localName: '简体中文', isCommon: true },
    { code: 'zh-TW', name: 'Chinese (Traditional)', localName: '繁体中文', isCommon: true },
    { code: 'zgh-MA', name: 'Standard Moroccan Tamazight', localName: '摩洛哥标准塔马齐格特语', isCommon: false },
    { code: 'sa-IN', name: 'Sanskrit', localName: '梵语', isCommon: false },
    { code: 'cnr-ME', name: 'Montenegrin', localName: '黑山语', isCommon: false },
    { code: 'mai-IN', name: 'Maithili', localName: '麦蒂利语', isCommon: false },
];
